# Generated by Django 4.2.2 on 2023-06-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('vendor', 'Vendor'), ('customer', 'Customer')], max_length=32, null=True),
        ),
    ]
